---
- name: Copy /etc/hostname.em1
  template:
    src: "hostname.em1.j2"
    dest: "/etc/hostname.em1"

- name: Copy /etc/hostname.em2
  template:
    src: "hostname.em2.j2"
    dest: "/etc/hostname.em2"

- name: Copy /etc/hostname.em3
  template:
    src: "hostname.em3.j2"
    dest: "/etc/hostname.em3"

- name: Create DHCP configuration file for em1
  template:
    src: dhcpd.conf.em1.j2
    dest: /etc/dhcpd.conf.em1

- name: Create DHCP configuration file for em2
  template:
    src: dhcpd.conf.em2.j2
    dest: /etc/dhcpd.conf.em2

- name: Create DHCP configuration file for em3
  template:
    src: dhcpd.conf.em3.j2
    dest: /etc/dhcpd.conf.em3

- name: Copy /etc/dhcpd.conf
  copy:
    src: "dhcpd.conf"
    dest: "/etc/dhcpd.conf"
  notify: Restart DHCP Service

- name: Copy /etc/rc.conf.local
  template:
    src: "rc.conf.local.j2"
    dest: "/etc/rc.conf.local"

- name: Enable IP forwarding on OpenBSD
  lineinfile:
    path: /etc/sysctl.conf.local
    line: 'net.inet.ip.forwarding=1'
  notify: Reload sysctl settings

- name: Copy PF configuration file
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf

- name: Ensure PF syntax is OK
  command: pfctl -nf /etc/pf.conf
  register: pf_syntax_check
  changed_when: false

- name: Reload PF
  command: pfctl -f /etc/pf.conf
  when: pf_syntax_check.stdout.find("syntax OK") != -1

- name: Enable PF
  command: pfctl -e
  when: pf_syntax_check.stdout.find("syntax OK") != -1

- name: Enable DHCP service
  service:
    name: dhcpd
    state: started
    enabled: yes

handlers:
  - name: Restart DHCP Service
    service:
      name: dhcpd
      state: restarted

  - name: Reload sysctl settings
  command: sysctl -w net.inet.ip.forwarding=1