---
- hosts: localhost
  become: yes
  roles:
    - common
    - pf
    - restart_network

  handlers:
    - name: Reload PF
      command: pfctl -f /etc/pf.conf
      notify: Enable PF

    - name: Enable PF
      command: pfctl -e